name: Daily Active ETF Monitor

on:
  schedule:
    # Run at 10:00 UTC (which is 18:00 Taiwan time)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Run Monitor Script
      run: python monitor_active_etfs.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add etf_data/*.csv etf_data/*.html index.html
        # Check if there are changes before committing
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto-update ETF data and report: $(date +'%Y-%m-%d')"
          git push
        fi
